/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controladora.Controladora;
import Controladora.GestionCorredores;
import Modelo.Corredor;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.builtin.stringvalidation.Integer_no_negativo_no_requerido;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author adan
 */
public class DialogAltaCorredor extends javax.swing.JDialog {

    private Corredor corredorModificar;
    /**
     * Creates new form DialogAltaCorredor
     */
    public DialogAltaCorredor(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.botonCrearCorredor.setEnabled(false);
        ValidationGroup grupo = validation.getValidationGroup();
        grupo.add(this.dni, StringValidators.REQUIRE_NON_EMPTY_STRING);
        grupo.add(this.nombre, StringValidators.REQUIRE_NON_EMPTY_STRING);
        grupo.add(this.telefono,new Integer_no_negativo_no_requerido());
        validation.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if(validation.getProblem()==null)
                    botonCrearCorredor.setEnabled(true);
                else
                    botonCrearCorredor.setEnabled(false);
            }
        });
    }
    
    public DialogAltaCorredor(java.awt.Dialog parent, boolean modal,Corredor corredor) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.botonCrearCorredor.setEnabled(false);
        this.botonCrearCorredor.setText("modificar");
        ValidationGroup grupo = validation.getValidationGroup();
        grupo.add(this.dni, StringValidators.REQUIRE_NON_EMPTY_STRING);
        grupo.add(this.nombre, StringValidators.REQUIRE_NON_EMPTY_STRING);
        grupo.add(this.telefono,new Integer_no_negativo_no_requerido());
        validation.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if(validation.getProblem()==null)
                    botonCrearCorredor.setEnabled(true);
                else
                    botonCrearCorredor.setEnabled(false);
            }
        });
        this.dni.setText(corredor.getDNI());
        this.nombre.setText(corredor.getNombre());
        this.direccion.setText(corredor.getDireccion());
        this.telefono.setText(String.valueOf(corredor.getTelef()));
        this.fecha.setValue(corredor.getFechaNac());
        this.corredorModificar=corredor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonCrearCorredor = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        validation = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        fecha = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.jLabel1.text")); // NOI18N

        botonCrearCorredor.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.botonCrearCorredor.text")); // NOI18N
        botonCrearCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCorredorActionPerformed(evt);
            }
        });

        botonLimpiar.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.botonLimpiar.text")); // NOI18N
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.jLabel6.text")); // NOI18N

        dni.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.dni.text")); // NOI18N

        nombre.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.nombre.text")); // NOI18N

        direccion.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.direccion.text")); // NOI18N

        telefono.setText(org.openide.util.NbBundle.getMessage(DialogAltaCorredor.class, "DialogAltaCorredor.telefono.text")); // NOI18N

        fecha.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCrearCorredor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dni)
                            .addComponent(nombre)
                            .addComponent(direccion)
                            .addComponent(telefono)
                            .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(validation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearCorredor)
                    .addComponent(botonLimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        this.dni.setText("");
        this.nombre.setText("");
        this.direccion.setText("");
        this.telefono.setText("");
        this.fecha.setValue(new Date());
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonCrearCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCorredorActionPerformed
        // TODO add your handling code here:
        
        GestionCorredores gestion = Controladora.getInstance().getGestionCorredores();
        int numTelefono=(!this.telefono.getText().trim().equalsIgnoreCase(""))?
                Integer.parseInt(this.telefono.getText().trim()):0;
        if(corredorModificar==null){
        if(gestion.nuevoCorredor(this.dni.getText(),this.nombre.getText(),
                this.direccion.getText(),numTelefono,(Date)this.fecha.getValue())){
            JOptionPane.showMessageDialog(this, "se ha añadido un corredor");
            botonLimpiarActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(this, "ya existe el corredor",null,JOptionPane.ERROR_MESSAGE);
        }
            
        }else{
            if(!gestion.getCorredores().contains(new Corredor(dni.getText().trim()))||
                    corredorModificar.getDNI().equals(dni.getText().trim())){
                corredorModificar.setTelef(numTelefono);
                corredorModificar.setDNI(dni.getText().trim());
                corredorModificar.setFechaNac((Date) fecha.getValue());
                corredorModificar.setDireccion(direccion.getText().trim());
                corredorModificar.setNombre(nombre.getText().trim());
                dispose();
            }else
                JOptionPane.showMessageDialog(this, "ya existe el corredor",null,JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_botonCrearCorredorActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCorredor;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private javax.swing.JSpinner fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validation;
    // End of variables declaration//GEN-END:variables
}
