/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controladora.Controladora;
import Modelo.Carrera;
import Modelo.Corredor;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author alumnop
 */
public class SeleccionCorredores extends javax.swing.JDialog {

    private int contadorPulsaciones,ultimoPulsado;
    private Controladora con;
    private Map<String, Corredor> corredores;
    private int numMaximo;

    
    /**
     * Creates new form SeleccionCorredores
     */
    public SeleccionCorredores(java.awt.Dialog parent, boolean modal, Controladora con, Map<String, Corredor> corredores, int numMaximo) {
        super(parent, modal);
        initComponents();
        this.con = con;
        this.con.rellenarListaCorredores(lista);
        this.corredores = corredores;
        this.numMaximo=numMaximo;
        this.contadorPulsaciones=0;
        this.ultimoPulsado=-1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        seleccionButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(SeleccionCorredores.class, "SeleccionCorredores.jLabel1.text")); // NOI18N

        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        seleccionButon.setText(org.openide.util.NbBundle.getMessage(SeleccionCorredores.class, "SeleccionCorredores.seleccionButon.text")); // NOI18N
        seleccionButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(seleccionButon))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionButon)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionButonActionPerformed
        // TODO add your handling code here:
        if (lista.getSelectedIndices().length == 0) {
            
            JOptionPane.showMessageDialog(this, "No has seleccionado nada");
        } else if(lista.getSelectedIndices().length <= this.numMaximo) {
            int contador=0;
            for (int selectedIndice : lista.getSelectedIndices()) {
               if (corredores.put(selectedIndice+"",con.getCorredores().get(selectedIndice)) ==null)
                contador++;
            }
            if(contador!=0)
                JOptionPane.showMessageDialog(this, "se han añadido "+contador+" corredores");
            else
                JOptionPane.showMessageDialog(this, "se ha terminado de añadir jugadores");
            dispose();
        }else
            JOptionPane.showMessageDialog(this, "Has seleccionado mas corredores del maximo");
        
    }//GEN-LAST:event_seleccionButonActionPerformed

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        // TODO add your handling code here:
        if(this.numMaximo>=this.corredores.size()+1){
            if(this.contadorPulsaciones==1){
                if(this.ultimoPulsado==this.lista.getSelectedIndex()){
                    boolean annadir =corredores.put(lista.getSelectedIndex()+"", con.getCorredores().get(lista.getSelectedIndex()))==null;
                    if(annadir)
                        JOptionPane.showMessageDialog(this,"se ha añadido un jugador");
                    this.ultimoPulsado=-1;
                    this.contadorPulsaciones=0;
                }else{
                    this.contadorPulsaciones=0;
                    this.ultimoPulsado=this.lista.getSelectedIndex();
                }
            }else{
                this.contadorPulsaciones=1;
                this.ultimoPulsado=this.lista.getSelectedIndex();
            }
        }else
            JOptionPane.showMessageDialog(this, "No puedes añadir mas personas que el máximo");
                
    }//GEN-LAST:event_listaMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    private javax.swing.JButton seleccionButon;
    // End of variables declaration//GEN-END:variables
}
